library(shiny)
library(bslib)

ui <- page_sidebar(
  title = "Package Installation Verification",
  sidebar = sidebar(
    h4("Installed Packages"),
    p("This app demonstrates that grithub, S4Vectors and magick are properly installed."),
    actionButton("test_grithub", "Test grithub", class = "btn-primary mb-2"),
    actionButton("test_s4", "Test S4Vectors", class = "btn-primary mb-2"),
    actionButton("test_magick", "Test magick", class = "btn-success mb-2")
  ),
  card(
    card_header("grithub Test Results"),
    verbatimTextOutput("grithub_results")
  ),
  card(
    card_header("S4Vectors Test Results"),
    verbatimTextOutput("s4_results")
  ),
  card(
    card_header("magick Test Results"),
    verbatimTextOutput("magick_results")
  ),
  card(
    card_header("Generated Image"),
    imageOutput("test_image")
  )
)

server <- function(input, output, session) {
  
  # Test grithub functionality
  observeEvent(input$test_grithub, {
    output$grithub_results <- renderText({
      tryCatch({
        paste0("grithub package loaded successfully!\n", grithub::hello())
      }, error = function(e) {
        paste("Error testing grithub:", e$message)
      })
    })
  })
  
  # Test S4Vectors functionality
  observeEvent(input$test_s4, {
    output$s4_results <- renderText({
      tryCatch({
        # Create a simple S4Vector
        vec <- c(1, 2, 3, 4, 5)
        s4_vec <- S4Vectors::Rle(vec)
        
        paste0(
          "S4Vectors package loaded successfully!\n",
          "Package version: ", packageVersion("S4Vectors"), "\n",
          "Created Rle object: ", toString(as.vector(s4_vec)), "\n",
          "Length: ", length(s4_vec), "\n",
          "Class: ", class(s4_vec)
        )
      }, error = function(e) {
        paste("Error testing S4Vectors:", e$message)
      })
    })
  })
  
  # Test magick functionality
  observeEvent(input$test_magick, {
    output$magick_results <- renderText({
      tryCatch({
        # Test basic magick functionality
        img <- magick::image_blank(200, 100, "lightblue")
        img <- magick::image_annotate(img, "Hello magick!", size = 30, color = "darkblue")
        
        # Save temporary image
        temp_file <- tempfile(fileext = ".png")
        magick::image_write(img, temp_file)
        
        # Display image in the app
        output$test_image <- renderImage({
          list(src = temp_file,
               contentType = 'image/png',
               width = 200,
               height = 100,
               alt = "Test image generated by magick")
        }, deleteFile = TRUE)
        
        paste0(
          "magick package loaded successfully!\n",
          "Package version: ", packageVersion("magick"), "\n",
          "Created test image with dimensions: 200x100\n",
          "Supported formats: ", length(magick::magick_config()$formats), " formats available\n",
          "Image generated and displayed below!"
        )
      }, error = function(e) {
        paste("Error testing magick:", e$message)
      })
    })
  })
}

shinyApp(ui = ui, server = server)
